#!/usr/bin/env python3
"""
Geocode studios from CSV using Nominatim (OpenStreetMap).
Outputs a TypeScript file with all geocoded studio pins.
"""
import csv
import json
import time
import urllib.request
import urllib.parse
import sys
import os

INPUT_CSV = os.path.join(os.path.dirname(__file__), "../src/data/studios-raw.csv")
OUTPUT_TS = os.path.join(os.path.dirname(__file__), "../src/data/csv-studios.ts")

STATE_ABBR = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
    "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
    "Florida": "FL", "Georgia": "GA", "Hawaii": "HI", "Idaho": "ID",
    "Illinois": "IL", "Indiana": "IN", "Iowa": "IA", "Kansas": "KS",
    "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD",
    "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS",
    "Missouri": "MO", "Montana": "MT", "Nebraska": "NE", "Nevada": "NV",
    "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY",
    "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK",
    "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC",
    "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT",
    "Vermont": "VT", "Virginia": "VA", "Washington": "WA", "West Virginia": "WV",
    "Wisconsin": "WI", "Wyoming": "WY", "District of Columbia": "DC",
}

def geocode(street, city, state):
    query = f"{street}, {city}, {state}, United States"
    encoded = urllib.parse.quote(query)
    url = f"https://nominatim.openstreetmap.org/search?q={encoded}&format=json&addressdetails=1&limit=1"
    req = urllib.request.Request(url, headers={"User-Agent": "newculture-studio-geocoder/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
        if data:
            return float(data[0]["lat"]), float(data[0]["lon"])
    except Exception as e:
        print(f"  Error: {e}", file=sys.stderr)
    # Fallback: try city+state only
    query2 = f"{city}, {state}, United States"
    encoded2 = urllib.parse.quote(query2)
    url2 = f"https://nominatim.openstreetmap.org/search?q={encoded2}&format=json&limit=1"
    req2 = urllib.request.Request(url2, headers={"User-Agent": "newculture-studio-geocoder/1.0"})
    try:
        with urllib.request.urlopen(req2, timeout=10) as resp2:
            data2 = json.loads(resp2.read())
        if data2:
            return float(data2[0]["lat"]), float(data2[0]["lon"])
    except Exception as e2:
        print(f"  Fallback error: {e2}", file=sys.stderr)
    return None, None

def escape_ts(s):
    if not s:
        return ""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", "")

def main():
    with open(INPUT_CSV, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    print(f"Processing {len(rows)} studios...", file=sys.stderr)
    results = []
    for i, row in enumerate(rows):
        title = row.get("title", "").strip()
        street = row.get("street", "").strip()
        city = row.get("city", "").strip()
        state_full = row.get("state", "").strip()
        state = STATE_ABBR.get(state_full, state_full[:2].upper() if state_full else "")
        website = row.get("website", "").strip()
        phone = row.get("phone", "").strip()
        rating = row.get("totalScore", "").strip()
        reviews = row.get("reviewsCount", "").strip()
        gmb_url = row.get("url", "").strip()

        if not title:
            continue

        print(f"[{i+1}/{len(rows)}] {title} — {city}, {state}", file=sys.stderr)
        lat, lng = geocode(street, city, state_full)

        if lat is None:
            print(f"  SKIP: could not geocode", file=sys.stderr)
            continue

        results.append({
            "title": title,
            "city": city,
            "state": state,
            "lat": lat,
            "lng": lng,
            "website": website,
            "phone": phone,
            "rating": float(rating) if rating else None,
            "reviews": int(reviews) if reviews and reviews.isdigit() else None,
            "gmb": gmb_url,
        })

        time.sleep(1.1)  # Nominatim rate limit: 1 req/sec

    print(f"\nGeocoded {len(results)}/{len(rows)} studios.", file=sys.stderr)

    # Write TypeScript
    lines = [
        '// AUTO-GENERATED by scripts/geocode-studios.py — do not edit manually',
        'import type { MapPin } from "@/components/ui/wireframe-dotted-globe";',
        '',
        'export const CSV_STUDIO_PINS: MapPin[] = [',
    ]
    for i, r in enumerate(results):
        rating_str = f", rating: {r['rating']}" if r['rating'] is not None else ""
        reviews_str = f", reviewCount: {r['reviews']}" if r['reviews'] is not None else ""
        website_str = f', website: "{escape_ts(r["website"])}"' if r['website'] else ""
        phone_str = f', phone: "{escape_ts(r["phone"])}"' if r['phone'] else ""
        gmb_str = f', gmbUrl: "{escape_ts(r["gmb"])}"' if r['gmb'] else ""
        lines.append(
            f'  {{ id: "csv_{i}", name: "{escape_ts(r["title"])}", '
            f'lat: {r["lat"]}, lng: {r["lng"]}, '
            f'city: "{escape_ts(r["city"])}", state: "{r["state"]}", '
            f'category: "studio"{rating_str}{reviews_str}{website_str}{phone_str}{gmb_str} }},'
        )
    lines.append('];')
    lines.append('')

    with open(OUTPUT_TS, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written to {OUTPUT_TS}", file=sys.stderr)

if __name__ == "__main__":
    main()
